# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 759c780d7ce84e5fe62345b16baf4a5922528a9b28d75d3c3b5eb8a12a633b065db153eefc660b15354db7de92d74e8510f26d17ad2d674a3666398285feb303

test:
  secret_key_base: 1c3cdd3689439e8cd6edd4f0c2093142651d93f9c47839855f8576208bb84884c341ece118ed7b7a5fa112ab15fe3e81b2777333bafb2df8d3aba179881f262b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
